kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{.Values.namespace.name}}
  labels:
    appglobal: {{ .Release.Name }}
data:
  #DEFINIÇÃO DE DESCRIÇÕES DO AMBIENTE
  BASE_UPDATE_DESCRICAO: {{ .Values.sei.BASE_UPDATE_DESCRICAO }}
  SIGLA_ORGAO: {{ .Values.sei.SIGLA_ORGAO }}
  SEI_NOME_SISTEMA_COMPLETO: {{ .Values.sei.SEI_NOME_SISTEMA_COMPLETO }}
  #DEFINIÇÃO DA URL BASE DO SEI
  SEI_SIP_DOMINIO: {{ .Values.sei.SEI_SIP_DOMINIO }}
  #DEFINIÇÃO DE INFORMAÇÕES DO BANCO DO SEI R SIP
  BANCO_SERVIDOR: {{ .Release.Name }}-{{ .Values.mysql.name }}
  BANCO_PORTA: {{ .Values.sei.BANCO_PORTA }}
  SEI_BANCO_NOME: {{ .Values.sei.SEI_BANCO_NOME }}
  SEI_BANCO_USUARIO: {{ .Values.sei.SEI_BANCO_USUARIO }}
  SIP_BANCO_NOME: {{ .Values.sei.SIP_BANCO_NOME }}
  SIP_BANCO_USUARIO: {{ .Values.sei.SIP_BANCO_USUARIO }}
  #DEFINIÇÃO REPOSITÓRIO DE ARMAZENAMENTO DOS ARQUIVOS
  SEI_REPOSITORIO_ARQUIVOS: {{ .Values.sei.SEI_REPOSITORIO_ARQUIVOS }}
  #DEFINIÇÃO CONTEXTO E URLS - CASO NAO SAIBA NÃO MODIFICAR
  SIP_CONTEXTO_LOGIN: {{ .Values.sei.SIP_CONTEXTO_LOGIN }}
  SIP_CONTEXTO_WSDL: {{ .Values.sei.SIP_CONTEXTO_WSDL }}
  BASE_UPDATE_CONTEXTO_INICIAL_SEI: {{ .Values.sei.BASE_UPDATE_CONTEXTO_INICIAL_SEI }}
  BASE_UPDATE_CONTEXTO_WEB_SERVICE: {{ .Values.sei.BASE_UPDATE_CONTEXTO_WEB_SERVICE }}
  SIP_CONTEXTO: {{ .Values.sei.SIP_CONTEXTO }}
  SEI_CONTEXTO: {{ .Values.sei.SEI_CONTEXTO }}
  #DEFINIÇÃO DE AMBIENTE PRODUÇÃO
  SEI_PRODUCAO: {{ .Values.sei.SEI_PRODUCAO }}
  SIP_PRODUCAO: {{ .Values.sei.SIP_PRODUCAO }}
  #DEFINIÇÃO DE SERVIDOR DE EMAIL
  EMAIL_SERVIDOR: {{ .Values.sei.EMAIL_SERVIDOR }}
  #DEFINIÇÃO PARA ACESSO AOS SERVIÇOS
  SOLR_SERVIDOR: http://{{ .Release.Name }}-{{ .Values.solr.name }}:8983/solr
  JODCONVERTER_SERVIDOR: http://{{ .Release.Name }}-{{ .Values.jod.name }}:8080/converter/service
  MEMCACHE_SERVIDOR: {{ .Release.Name }}-{{ .Values.memcache.name }}