kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.mysql.name }}
  namespace: {{.Values.namespace.name}}
  labels:
    app: {{ .Release.Name }}-{{ .Values.mysql.name }}
    appglobal: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.mysql.name }}
      deployment: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.mysql.name }}
        deployment: {{ .Values.mysql.name }}
    spec:
      volumes:
        - name: pvc-{{ .Release.Name }}-{{ .Values.mysql.volume.name }}
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-{{ .Values.mysql.volume.name }}
      {{ if eq .Values.sei.AMBIENTE "KUBERNETES" }}
      initContainers:
      - name: change-permissions-{{ .Release.Name }}-{{ .Values.mysql.name }}
        image: busybox:1.28
        command: ['sh', '-c', "chown -R 0:0 /var/lib/mysql"]
        volumeMounts:
          - name: pvc-{{ .Release.Name }}-{{ .Values.mysql.volume.name }}
            mountPath: /var/lib/mysql
      {{ end }}
      containers:
        - name: mysql
          {{ if eq .Values.sei.AMBIENTE "KUBERNETES" }}
          args: 
            - '--datadir=/var/lib/mysql'
          {{ else }}
          args:
            - '--datadir=/var/lib/mysql-sei'
          {{ end }}
          ports:
            - containerPort: 3306
              protocol: TCP
            - containerPort: 33060
              protocol: TCP
          {{ if eq .Values.sei.AMBIENTE "KUBERNETES" }}
          volumeMounts:
            - name: pvc-{{ .Release.Name }}-{{ .Values.mysql.volume.name }}
              mountPath: /var/lib/mysql
          {{ else }}
          volumeMounts:
            - name: pvc-{{ .Release.Name }}-{{ .Values.mysql.volume.name }}
              mountPath: /var/lib/mysql-sei
          {{ end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          image: {{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
      restartPolicy: Always
